### ISSUE TITLE
Legacy feature test script does not recognize `CC` environment variable

### ISSUE THREAD

**Issue by ryandesign** [att/ast#1107]
**Description of problem:**

Hello, the last time I built ksh from master on 20181014 it built fine, but trying to build the latest code as of 20190106 fails.

**Ksh version:**

20190106

**How reproducible:**

Always

**Steps to reproduce:**
1. Compile ksh on macOS High Sierra 10.13.6

**Actual results:**

```
[3/476] Compiling C object 'src/lib/libast/e416224@@ast@sta/conftab.c.o'.
FAILED: src/lib/libast/e416224@@ast@sta/conftab.c.o 
ccache /usr/bin/clang -Isrc/lib/libast/e416224@@ast@sta -Isrc/lib/libast -I../ast-8a5424fe72614392f0c989b67ad261270607b291/src/lib/libast -I. -I../ast-8a5424fe72614392f0c989b67ad261270607b291/ -I../ast-8a5424fe72614392f0c989b67ad261270607b291/src/lib/libast/include -Isrc/lib/libast/aso -I../ast-8a5424fe72614392f0c989b67ad261270607b291/src/lib/libast/aso -Isrc/lib/libast/cdt -I../ast-8a5424fe72614392f0c989b67ad261270607b291/src/lib/libast/cdt -Isrc/lib/libast/comp -I../ast-8a5424fe72614392f0c989b67ad261270607b291/src/lib/libast/comp -Isrc/lib/libast/sfio -I../ast-8a5424fe72614392f0c989b67ad261270607b291/src/lib/libast/sfio -Isrc/lib/libast/path -I../ast-8a5424fe72614392f0c989b67ad261270607b291/src/lib/libast/path -Isrc/lib/libast/port -I../ast-8a5424fe72614392f0c989b67ad261270607b291/src/lib/libast/port -Isrc/lib/libast/string -I../ast-8a5424fe72614392f0c989b67ad261270607b291/src/lib/libast/string -Isrc/lib/libast/misc -I../ast-8a5424fe72614392f0c989b67ad261270607b291/src/lib/libast/misc -Isrc/lib/libast/tm -I../ast-8a5424fe72614392f0c989b67ad261270607b291/src/lib/libast/tm -I/opt/local/include -Xclang -fcolor-diagnostics -pipe -Wall -Winvalid-pch -g -std=gnu99 -D_GNU_SOURCE -fno-strict-aliasing -Wextra -Wno-char-subscripts -Wno-sign-compare -fno-omit-frame-pointer -Werror=implicit -fno-inline -Os -arch x86_64 '-DUSAGE_LICENSE=""' -D_AST_no_spawnveg=1 -DGCC_4_1PLUS_64_BIT_MEMORY_ATOMIC_OPERATIONS_MODEL=1  -MD -MQ 'src/lib/libast/e416224@@ast@sta/conftab.c.o' -MF 'src/lib/libast/e416224@@ast@sta/conftab.c.o.d' -o 'src/lib/libast/e416224@@ast@sta/conftab.c.o' -c /path/to/build/src/lib/libast/comp/conftab.c
/path/to/build/src/lib/libast/comp/conftab.c:45:82: error: use of undeclared identifier '_SC_ABI_AIO_XFER_MAX'
{ "ABI_AIO_XFER_MAX", { 0U, 0 }, { 0U, 0 }, CONF_LIMIT, CONF_C, 1, CONF_sysconf, _SC_ABI_AIO_XFER_MAX },
                                                                                 ^
/path/to/build/src/lib/libast/comp/conftab.c:46:85: error: use of undeclared identifier '_SC_ABI_ASYNCHRONOUS_IO'
{ "ABI_ASYNCHRONOUS_IO", { 0U, 0 }, { 0U, 0 }, CONF_LIMIT, CONF_C, 1, CONF_sysconf, _SC_ABI_ASYNCHRONOUS_IO },
                                                                                    ^
/path/to/build/src/lib/libast/comp/conftab.c:47:78: error: use of undeclared identifier '_SC_ABI_ASYNC_IO'
{ "ABI_ASYNC_IO", { 0U, 0 }, { 0U, 0 }, CONF_LIMIT, CONF_C, 1, CONF_sysconf, _SC_ABI_ASYNC_IO },
                                                                             ^
/path/to/build/src/lib/libast/comp/conftab.c:48:71: error: use of undeclared identifier '_PC_ACL_ENABLED'
{ "ACL_ENABLED", { 0U, 0 }, { 0U, 0 }, 0, CONF_SUN, 1, CONF_pathconf, _PC_ACL_ENABLED },
                                                                      ^
/path/to/build/src/lib/libast/comp/conftab.c:52:38: error: use of undeclared identifier '_POSIX_AIO_PRIO_DELTA_MAX'
{ "AIO_PRIO_DELTA_MAX", { 0U, 0 }, { _POSIX_AIO_PRIO_DELTA_MAX, 0 }, CONF_LIMIT|CONF_MINMAX|CONF_UNDERSCORE|CONF_MINMAX_DEF, CONF_POSIX, 1, CONF_sysconf, _SC_AIO_PRIO_DELTA_MAX },
                                     ^
/path/to/build/src/lib/libast/comp/conftab.c:54:80: error: use of undeclared identifier 'SI_ARCHITECTURE'
{ "ARCHITECTURE", { 0, 0 }, { 0, 0 }, CONF_STRING, CONF_SVID, 1, CONF_sysinfo, SI_ARCHITECTURE },
                                                                               ^
/path/to/build/src/lib/libast/comp/conftab.c:58:30: error: use of undeclared identifier '_XOPEN_ATEXIT_MAX'
{ "ATEXIT_MAX", { 0U, 0 }, { _XOPEN_ATEXIT_MAX, 0 }, CONF_LIMIT|CONF_MINMAX|CONF_UNDERSCORE|CONF_MINMAX_DEF, CONF_XOPEN, 1, CONF_sysconf, _SC_ATEXIT_MAX },
                             ^
/path/to/build/src/lib/libast/comp/conftab.c:59:71: error: use of undeclared identifier '_SC_AUDIT'
{ "AUDIT", { 0U, 0 }, { 0U, 0 }, CONF_LIMIT, CONF_C, 1, CONF_sysconf, _SC_AUDIT },
                                                                      ^
/path/to/build/src/lib/libast/comp/conftab.c:60:82: error: use of undeclared identifier '_SC_AVAIL_PROCESSORS'
{ "AVAIL_PROCESSORS", { 0U, 0 }, { 0U, 0 }, CONF_LIMIT, CONF_C, 1, CONF_sysconf, _SC_AVAIL_PROCESSORS },
                                                                                 ^
/path/to/build/src/lib/libast/comp/conftab.c:61:71: error: use of undeclared identifier '_SC_AVPHYS_PAGES'
{ "AVPHYS_PAGES", { 0U, 0 }, { 0U, 0 }, 0, CONF_SUN, 1, CONF_sysconf, _SC_AVPHYS_PAGES },
                                                                      ^
/path/to/build/src/lib/libast/comp/conftab.c:67:76: error: use of undeclared identifier 'SI_BUSTYPES'
{ "BUSTYPES", { 0, 0 }, { 0, 0 }, CONF_STRING, CONF_SVID, 1, CONF_sysinfo, SI_BUSTYPES },
                                                                           ^
/path/to/build/src/lib/libast/comp/conftab.c:75:92: error: use of undeclared identifier '_SC_CKPT'
{ "CKPT", { 0U, 0 }, { 0U, 0 }, CONF_FEATURE|CONF_UNDERSCORE, CONF_POSIX, 1, CONF_sysconf, _SC_CKPT },
                                                                                           ^
/path/to/build/src/lib/libast/comp/conftab.c:77:149: error: use of undeclared identifier '_SC_CLOCKRES_MIN'
{ "CLOCKRES_MIN", { 0U, 0 }, { _POSIX_CLOCKRES_MIN, 0 }, CONF_MINMAX|CONF_UNDERSCORE|CONF_PREFIX_ONLY|CONF_MINMAX_DEF, CONF_POSIX, 1, CONF_sysconf, _SC_CLOCKRES_MIN },
                                                                                                                                                    ^
/path/to/build/src/lib/libast/comp/conftab.c:78:80: error: use of undeclared identifier '_SC_CLOCKS_PER_SEC'
{ "CLOCKS_PER_SEC", { 0U, 0 }, { 0U, 0 }, CONF_LIMIT, CONF_C, 1, CONF_sysconf, _SC_CLOCKS_PER_SEC },
                                                                               ^
/path/to/build/src/lib/libast/comp/conftab.c:82:78: error: use of undeclared identifier '_SC_CPU_KEYBITS1'
{ "CPU_KEYBITS1", { 0U, 0 }, { 0U, 0 }, CONF_LIMIT, CONF_C, 1, CONF_sysconf, _SC_CPU_KEYBITS1 },
                                                                             ^
/path/to/build/src/lib/libast/comp/conftab.c:83:77: error: use of undeclared identifier '_SC_CPU_VERSION'
{ "CPU_VERSION", { 0U, 0 }, { 0U, 0 }, CONF_LIMIT, CONF_C, 1, CONF_sysconf, _SC_CPU_VERSION },
                                                                            ^
/path/to/build/src/lib/libast/comp/conftab.c:87:127: error: use of undeclared identifier '_SC_2_C_VERSION'
{ "C_VERSION", { 0U, 0 }, { 0U, 0 }, CONF_DEFER_CALL|CONF_DEFER_MM|CONF_FEATURE|CONF_UNDERSCORE, CONF_POSIX, 2, CONF_sysconf, _SC_2_C_VERSION },
                                                                                                                              ^
/path/to/build/src/lib/libast/comp/conftab.c:88:69: error: use of undeclared identifier '_SC_DATAKEYS_MAX'
{ "DATAKEYS_MAX", { 0U, 0 }, { 0U, 0 }, 0, CONF_C, 1, CONF_sysconf, _SC_DATAKEYS_MAX },
                                                                    ^
/path/to/build/src/lib/libast/comp/conftab.c:91:81: error: use of undeclared identifier '_SC_EQUIV_CLASS_MAX'
{ "EQUIV_CLASS_MAX", { 0U, 0 }, { 0U, 0 }, CONF_LIMIT, CONF_C, 1, CONF_sysconf, _SC_EQUIV_CLASS_MAX },
                                                                                ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
```

**Expected results:**

No errors

**Additional info:**

**Comment by ryandesign** [comment]
> the last time I built ksh from master on 20181014 it built fine, but trying to build the latest code as of 20190106 fails

In fact, the 20181014 code doesn't build now either; same error. Not sure what changed.

**Comment by ryandesign** [comment]
Here's what meson said, in case it's helpful:

```
The Meson build system
Version: 0.49.0
Source dir: /path/to/ast-8a5424fe72614392f0c989b67ad261270607b291
Build dir: /path/to/build
Build type: native build
Project name: ksh93
Project version: undefined
Appending CFLAGS from environment: '-pipe -Os -arch x86_64'
Appending LDFLAGS from environment: '-L/opt/local/lib -Wl,-headerpad_max_install_names -arch x86_64'
Appending CPPFLAGS from environment: '-I/opt/local/include'
Native C compiler: /usr/bin/clang (clang 9.1.0 "Apple LLVM version 9.1.0 (clang-902.0.39.2)")
Build machine cpu family: x86_64
Build machine cpu: x86_64
Compiler for C supports arguments -Werror=implicit: YES
Checking for size of "void*" : 8
Checking for size of "int" : 4
Checking for size of "long" : 8
Checking for size of "size_t" : 8
Checking for size of "off_t" : 8
Checking for size of "int32_t" : 4
Checking for size of "wchar_t" : 4
Compiler for C supports link arguments -Wl,--export-dynamic: NO
Checking for size of "long long" : 8
Library m found: YES
Library dl found: YES
Library execinfo found: NO
Library iconv found: YES
Library catgets found: NO
Has header "execinfo.h" : YES
Has header "unistd.h" : YES
Has header "stdlib.h" : YES
Has header "malloc.h" : NO
Has header "filio.h" : NO
Has header "sys/filio.h" : YES
Checking for function "lchmod" : YES
Checking for function "sigqueue" : NO
Checking for function "isnanl" : NO
Checking for function "eaccess" : NO
Checking for function "euidaccess" : NO
Checking for function "faccessat" : YES
Checking for function "mkostemp" : YES
Checking for function "strlcat" : YES
Checking for function "utimensat" : YES
Checking for function "sysinfo" : NO
Checking for function "pipe2" : NO
Checking for function "syncfs" : NO
Checking for function "nexttowardl" with dependency -lm: YES
Checking for function "expm1l" with dependency -lm: YES
Checking for function "log1pl" with dependency -lm: YES
Checking for function "remainderl" with dependency -lm: YES
Checking for function "log2l" with dependency -lm: YES
Checking for function "tgammal" with dependency -lm: YES
Checking for function "lgammal" with dependency -lm: YES
Checking if "fchmod() after socketpair() shutdown()" runs: NO (1)
Checking if "max signal number" runs: YES
Checking whether type "struct stat" has member "st_mtim" : NO
Checking whether type "struct stat" has member "st_mtimespec" : YES
Checking if "poll() exists and is worth using" runs: NO (1)
Checking if "posix_spawn() exists and is worth using" runs: YES
Checking if "Check if -D_FILE_OFFSET_BITS=64 works with fts functions" compiles: YES
Program tput found: YES (/opt/local/bin/tput)
Program ed found: YES (/bin/ed)
Program atos found: YES (/usr/bin/atos)
Program addr2line found: NO
Has header "dl.h" : NO
Has header "dlfcn.h" : YES
Has header "dll.h" : NO
Has header "rld_interface.h" : NO
Has header "mach-o/dyld.h" : YES
Has header "sys/ldr.h" : NO
Library dl found: YES
Checking for function "dlopen" with dependency -ldl: YES
Checking for function "dllload" with dependency -ldl: NO
Checking for function "loadbind" with dependency -ldl: NO
Checking if "_DYNAMIC check" runs: DID NOT COMPILE
Checking for function "clock_gettime" : YES
Checking for function "gettimeofday" : YES
Has header "sys/syscall.h" : YES
Has header "sys/systeminfo.h" : NO
Has header "sys/syssgi.h" : NO
Checking for function "syscall" : YES
Checking for function "systeminfo" : NO
Configuring config_ast.h using configuration
Checking if "gcc 4.1+ 64 bit memory atomic operations model" links: YES
Build targets in project: 96
Found ninja-1.8.2 at /opt/local/bin/ninja
```

**Comment by siteshwar** [comment]
I suspect something broke with newest release of `meson`. It would be a good idea to try a build with `meson 0.48`.

**Comment by krader1961** [comment]
Works for me on macOS 10.12, 10.13, and 10.14 using Meson 0.46 and 0.48. The symbols that can't be resolved don't exist on macOS. The corresponding entries in *conftab.c* should have `CONF_nop, -1` as the final two args. Note that *conftab.c* is generated by the borderline incomprehensible *src/lib/libast/comp/conf.sh* script. Something on your system is causing that script to think those symbols are valid.

Look at your *meson-logs/meson-log.txt* configuration log. Find this line:

```
conf.sh: read /Users/krader/projects/3rd-party/ast/src/lib/libast/comp/conf.tab
```

Following that should be lines like this:

```
conf.sh: probe for ABI_AIO_XFER_MAX <limits.h> value
/var/folders/6t/t624jkmx7cbb9t35vzvjwj180000gn/T/ksh.XXXXXX.tQFeYFhy/conf.c:20:49: error: use of undeclared identifier 'ABI_AIO_XFER_MAX'
        printf("%lu\n", (unsigned _ast_intmax_t)ABI_AIO_XFER_MAX);
                                                ^
1 error generated.
```

**Comment by krader1961** [comment]
@ryandesign Does the problem occur if you `git clean -dfx; mkdir build` to ensure you aren't working with stale build artifacts? That shouldn't be necessary but I'm paranoid and always start with a clean slate if I'm getting unexpected results.

**Comment by ryandesign** [comment]
> It would be good idea to try a build with `meson 0.48`.

I did try that already; no change.

> Does the problem occur if you `git clean -dfx; mkdir build` to ensure you aren't working with stale build artifacts?

MacPorts builds from a clean directory already.

> Look at your _meson-logs/meson-log.txt_ configuration log

Thanks; I'm not familiar with meson and didn't know that logfile existed. I now see that the problem is that it's using `cc`, which on my system is a [script](https://trac.macports.org/wiki/UsingTheRightCompiler#testing) that emits an error, for the purpose of finding build systems that don't use the compiler I told them to. (I must not have had that script in place when I built ksh last.) Looks like the use of `cc` is hardcoded in scripts/libast_prereq.sh. Can it be changed to use the compiler that was specified to meson via the `CC` environment variable?

**Comment by ryandesign** [comment]
Thanks!
