### ISSUE TITLE
compilation failure on macOS: implicit declaration of mkostemp

### ISSUE THREAD

**Issue by McDutchie** [att/ast#976]
System: Mac OS X 10.11, Apple LLVM version 8.0.0 (clang-800.0.42.1)

Apparently the fallback mkostemp() defined in `src/lib/libast/misc/fallbacks.c` is not used.

This appears to have been introduced by commit 1788840aa41dd7dd040f06cfc7287d2c253b1bc4.

````
$ LC_ALL=C ninja -C build
ninja: Entering directory `build'
[1/95] Compiling C object 'src/lib/libast/src@lib@libast@@ast@sta/path_pathtemp.c.o'.
FAILED: src/lib/libast/src@lib@libast@@ast@sta/path_pathtemp.c.o 
ccache cc -Isrc/lib/libast/src@lib@libast@@ast@sta -Isrc/lib/libast -I../src/lib/libast -I. -I../ -I../src/lib/libast/include -Isrc/lib/libast/aso -I../src/lib/libast/aso -Isrc/lib/libast/cdt -I../src/lib/libast/cdt -Isrc/lib/libast/comp -I../src/lib/libast/comp -Isrc/lib/libast/sfio -I../src/lib/libast/sfio -Isrc/lib/libast/path -I../src/lib/libast/path -Isrc/lib/libast/port -I../src/lib/libast/port -Isrc/lib/libast/string -I../src/lib/libast/string -Isrc/lib/libast/misc -I../src/lib/libast/misc -Isrc/lib/libast/tm -I../src/lib/libast/tm -Xclang -fcolor-diagnostics -pipe -Wall -Winvalid-pch -g -std=gnu99 -D_GNU_SOURCE -fno-strict-aliasing -Wextra -Wno-char-subscripts -Wno-sign-compare -fno-omit-frame-pointer -Werror=implicit -fno-inline '-DUSAGE_LICENSE=""' -D_AST_no_spawnveg=1 -DGCC_4_1PLUS_64_BIT_MEMORY_ATOMIC_OPERATIONS_MODEL=1  -MD -MQ 'src/lib/libast/src@lib@libast@@ast@sta/path_pathtemp.c.o' -MF 'src/lib/libast/src@lib@libast@@ast@sta/path_pathtemp.c.o.d' -o 'src/lib/libast/src@lib@libast@@ast@sta/path_pathtemp.c.o' -c ../src/lib/libast/path/pathtemp.c
../src/lib/libast/path/pathtemp.c:92:15: error: implicit declaration of function 'mkostemp' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
        *fd = mkostemp(template, open_flags);
              ^
../src/lib/libast/path/pathtemp.c:92:15: note: did you mean 'mkstemp'?
/usr/include/unistd.h:675:6: note: 'mkstemp' declared here
int      mkstemp(char *);
         ^
1 error generated.
[2/95] Generating version.h with a custom command.
ninja: build stopped: subcommand failed.
````
