### ISSUE TITLE
Undefined symbols _iconv_close

### ISSUE THREAD

**Issue by ryandesign** [att/ast#932]
**Description of problem:**

Hi, I'm a developer with MacPorts, trying to fix the problem that we haven't been able to build ksh93 for years. I see you've switched to the meson build system, but when I try to build the latest code on macOS High Sierra, I get failures due to undefined symbol `_iconv_close`. I know that libiconv builds in different ways on different systems or in different configurations, and sometimes, as is the case in MacPorts, the symbol is actually called `_libiconv_close`. I don't know how projects are supposed to structure their code to accommodate both possibilities.

**Ksh version:**

Latest code as of 2018-10-05, 1faa299aa9bf68f31f0ff9283b683ced5daf0e81

**How reproducible:**

Always

**Steps to reproduce:**
1. On macOS, with MacPorts installed, check out the code, run `meson` and `ninja`.

**Actual results:**

```
[338/493] Linking target src/cmd/tests/aso/tlock.c.
FAILED: src/cmd/tests/aso/tlock.c 
ccache /usr/bin/clang  -o src/cmd/tests/aso/tlock.c 'src/cmd/tests/aso/src@cmd@tests@aso@@tlock.c@exe/tlock.c.o' -L/opt/local/lib -Wl,-dead_strip_dylibs -Wl,-headerpad_max_install_names -pipe -Os -arch x86_64 -Wl,-headerpad_max_install_names -arch x86_64 src/lib/libast/libast.a src/lib/libast/libenv.a -lpthread -lm -liconv -ldl -Wl,-headerpad_max_install_names -Wl,-rpath,/path/to/build/src/lib/libast  
Undefined symbols for architecture x86_64:
  "_iconv_close", referenced from:
      _init_ast_struct in libast.a(comp_setlocale.c.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Expected results:**

Successful compilation

**Additional info:**

**Comment by etscrivner** [comment]
Hey @ryandesign, thanks for the bug report.

I just tried a fresh build on macOS High Sierra (v10.13.6) and was not able to reproduce this. I ran the following:

```
meson build --buildtype=release
cd build
ninja
```

The libiconv is v2.4.0 and comes installed by default on macOS High Sierra in `/usr/lib`. It sounds like you may have another version of libiconv installed. If so, it may be worth trying the following and then regenerating the build directory using the steps above:

```
sudo port -f deactivate libiconv
```

**Comment by ryandesign** [comment]
Yes, I'm not surprised that it would work with the system iconv, since the system iconv's symbols are known to be named like `_iconv_close`.

```
$ nm /usr/lib/libiconv.dylib |egrep ' _(lib)?iconv(_close|_open)?$'
0000000000002b15 T _iconv
0000000000002b37 T _iconv_close
000000000000188d T _iconv_open
```

However, I use MacPorts, and its libiconv names its symbols like `_libiconv_close`.

```
$ nm /opt/local/lib/libiconv.dylib |egrep ' _(lib)?iconv(_close|_open)?$'
0000000000002f72 T _libiconv
0000000000002f94 T _libiconv_close
0000000000001c5c T _libiconv_open
```

I can't deactivate libiconv because meson uses python which uses gettext which uses libiconv. I am the maintainer of libiconv in MacPorts and I don't think we're doing anything wrong or unusual in the way we've built libiconv; everything else we have in MacPorts is able to use it.

**Comment by krader1961** [comment]
See *features/meson.build*:

```
# Under Cygwin the iconv shared library exports the symbols we need with a
# `lib` prefix. So we don't want the LIBICONV_PLUG behavior on that platform.
# On others we either want this or it's a no-op.
if not (system == 'cygwin' or system == 'openbsd')
    feature_data.set('LIBICONV_PLUG', 1)
endif
```

The question is how to determine this without having to special-case system names as shown above.

Also, are you certain that ksh is including the MacPorts *iconv.h* header rather than the macOS header?

**Comment by ryandesign** [comment]
> Also, are you certain that ksh is including the MacPorts _iconv.h_ header rather than the macOS header?

I believe so. I'm using the standard MacPorts method of using meson, which sets a number of environment variables, including putting `/opt/local/include` in `CPATH`, `/opt/local/lib` in `LIBRARY_PATH`, `-I/opt/local/include` in `CPPFLAGS`, and `-L/opt/local/lib` in `LDFLAGS`. This should mean that `#include <iconv.h>` will find /opt/local/include/iconv.h.

**Comment by krader1961** [comment]
FWIW, the current "solution" shown in my previous comment was something I added out of expediency when I started trying to get ksh to build on non-Linux systems after we switched to Meson. I had no reason to think that was the correct way to deal with the issue.

The expedient solution would be to special-case MacPorts like we do Cygwin and OpenBSD. But it's not clear how to do that. And in any case we probably should be doing a proper feature test via building a stub program rather than testing the system name (`uname -s`) as shown in my previous comment. So the question is what does GNU autoconf or Cmake do in this regard?

**Comment by ryandesign** [comment]
> ```
> if not (system == 'cygwin' or system == 'openbsd')
>     feature_data.set('LIBICONV_PLUG', 1)
> endif
> ```

Thanks for pointing this out. Removing this block allows the build to succeed. I can just patch it out for now in MacPorts.

> The expedient solution would be to special-case MacPorts like we do Cygwin and OpenBSD. But it's not clear how to do that.

I don't think there's an approved way to know whether you're being built by MacPorts, probably because you shouldn't need to know that. :) And it's not whether you're being built by MacPorts that matters; what matters is whether the libiconv you're linking with was. And we're not building libiconv in a particularly unusual way; a libiconv built manually by the user or installed by another package manager would likely behave the same way.
