### PR TITLE
Remove feature tests and compatiblility code for stdio and wchar

### PR DESCRIPTION
**Pull request by siteshwar**
This pull request is currently work in progress and should not be merged until all tests pass.

EDIT: It should be ready to merge now.

### CODE REVIEW

**Comment by siteshwar** [comment]
```
test locale begins at 2017-11-07+17:30:46
    locale.sh[209]: multibyte variable definition/expansion failed -- expected 'OK', got '/home/situ/upstream/ast/arch/linux.i386-64/bin/ksh: syntax error at line 1: `å' unexpected'
    locale.sh[211]: multibyte ksh function definition/execution failed -- expected 'OK', got '/home/situ/upstream/ast/arch/linux.i386-64/bin/ksh: å¤©: invalid function name'
    locale.sh[213]: multibyte posix function definition/execution failed -- expected 'OK', got '/home/situ/upstream/ast/arch/linux.i386-64/bin/ksh: å¤©: invalid function name'
    locale.sh[215]: multibyte variable definition/expansion failed -- expected 'OK', got '/home/situ/upstream/ast/arch/linux.i386-64/bin/ksh: syntax error at line 1: `å' unexpected'
    locale.sh[217]: multibyte ksh function definition/execution failed -- expected 'OK', got '/home/situ/upstream/ast/arch/linux.i386-64/bin/ksh: å¤©: invalid function name'
    locale.sh[219]: multibyte posix function definition/execution failed -- expected 'OK', got '/home/situ/upstream/ast/arch/linux.i386-64/bin/ksh: å¤©: invalid function name'
/home/situ/upstream/ast/arch/linux.i386-64/bin/ksh: (debug,ksh,libshell,a<2A@>z=123: invalid variable name)
    locale.sh[267]: multibyte debug locale $a<2A@>z failed -- expected '123', got ''
test locale failed at 2017-11-07+17:30:46 with exit code 7 [ 38 tests 7 errors ]
test locale(shcomp) begins at 2017-11-07+17:30:46
    shcomp-locale.ksh[209]: multibyte variable definition/expansion failed -- expected 'OK', got '/home/situ/upstream/ast/arch/linux.i386-64/bin/ksh: syntax error at line 1: `å' unexpected'
    shcomp-locale.ksh[211]: multibyte ksh function definition/execution failed -- expected 'OK', got '/home/situ/upstream/ast/arch/linux.i386-64/bin/ksh: å¤©: invalid function name'
    shcomp-locale.ksh[213]: multibyte posix function definition/execution failed -- expected 'OK', got '/home/situ/upstream/ast/arch/linux.i386-64/bin/ksh: å¤©: invalid function name'
    shcomp-locale.ksh[215]: multibyte variable definition/expansion failed -- expected 'OK', got '/home/situ/upstream/ast/arch/linux.i386-64/bin/ksh: syntax error at line 1: `å' unexpected'
    shcomp-locale.ksh[217]: multibyte ksh function definition/execution failed -- expected 'OK', got '/home/situ/upstream/ast/arch/linux.i386-64/bin/ksh: å¤©: invalid function name'
    shcomp-locale.ksh[219]: multibyte posix function definition/execution failed -- expected 'OK', got '/home/situ/upstream/ast/arch/linux.i386-64/bin/ksh: å¤©: invalid function name'
/home/situ/upstream/ast/arch/linux.i386-64/bin/ksh: (debug,ksh,libshell,a<2A@>z=123: invalid variable name)
    shcomp-locale.ksh[267]: multibyte debug locale $a<2A@>z failed -- expected '123', got ''
test locale(shcomp) failed at 2017-11-07+17:30:46 with exit code 7 [ 38 tests 7 errors ]
```

These tests failures are caused by change in how identifier names are checked for validity. 
[This check](https://github.com/siteshwar/ast/blob/e3b430462b20c81bfa760c24c086661ef4b0fd91/src/cmd/ksh93/sh/name.c#L1511) is failing under ```C.utf-8``` locale. The difference is caused by use of ```iswalpha``` funtion (from glibc) rather than [utf8_alpha](https://github.com/siteshwar/ast/blob/e3b430462b20c81bfa760c24c086661ef4b0fd91/src/lib/libast/comp/setlocale.c#L2166) function.

It can be easily reproduced by below test script :

```
export LC_ALL="C.utf-8"
#export LC_ALL="en_US.utf8"
locale

天=OK
echo $天
```

This script will work with ```en_US.utf8``` locale, but not with ```C.utf-8```.

**Comment by siteshwar** [comment]
Also, some tests are failing under ```zh_CN.GB18030``` locale.

```
test wchar begins at 2017-11-07+17:37:49
    wchar.sh[60]: zh_CN.GB18030 nounicodeliterals FAILED -- expected '0000000 24 27 e2 82 ac 27 0a', got '0000000 24 27 5c 78 61 63 27 0a'
    wchar.sh[63]: zh_CN.GB18030 (nounicodeliterals) FAILED -- expected '0000000 24 27 e2 82 ac 27 0a', got '0000000 24 27 5c 78 61 63 27 0a'
    wchar.sh[66]: zh_CN.GB18030 unicode FAILED -- expected $'\u[20ac]', got $'\xac'
    wchar.sh[69]: zh_CN.GB18030 (unicodeliterals) FAILED -- expected $'\u[20ac]', got $'\xac'
test wchar failed at 2017-11-07+17:37:49 with exit code 4 [ 4 tests 4 errors ]
test wchar(C.UTF-8) begins at 2017-11-07+17:37:49
    wchar.sh[60]: zh_CN.GB18030 nounicodeliterals FAILED -- expected '0000000 24 27 e2 82 ac 27 0a', got '0000000 24 27 5c 78 61 63 
27 0a'
    wchar.sh[63]: zh_CN.GB18030 (nounicodeliterals) FAILED -- expected '0000000 24 27 e2 82 ac 27 0a', got '0000000 24 27 5c 78 61 63 27 0a'
    wchar.sh[66]: zh_CN.GB18030 unicode FAILED -- expected $'\u[20ac]', got $'\xac'
    wchar.sh[69]: zh_CN.GB18030 (unicodeliterals) FAILED -- expected $'\u[20ac]', got $'\xac'
test wchar(C.UTF-8) failed at 2017-11-07+17:37:49 with exit code 4 [ 4 tests 4 errors ]
test wchar(shcomp) begins at 2017-11-07+17:37:49
    shcomp-wchar.ksh[60]: zh_CN.GB18030 nounicodeliterals FAILED -- expected '0000000 24 27 e2 82 ac 27 0a', got '0000000 24 27 5c 78 61 63 27 0a'
    shcomp-wchar.ksh[63]: zh_CN.GB18030 (nounicodeliterals) FAILED -- expected '0000000 24 27 e2 82 ac 27 0a', got '0000000 24 27 5c 78 61 63 27 0a'
    shcomp-wchar.ksh[66]: zh_CN.GB18030 unicode FAILED -- expected $'\u[20ac]', got $'\xac'
    shcomp-wchar.ksh[69]: zh_CN.GB18030 (unicodeliterals) FAILED -- expected $'\u[20ac]', got $'\xac'
test wchar(shcomp) failed at 2017-11-07+17:37:49 with exit code 4 [ 4 tests 4 errors ]
```
These are currently skipped in Fedora because langpack for ```zh_CN.GB18030```  is missing.

**Comment by krader1961** [comment]
FWIW, I am hoping we can remove the ksh dependency on the SFIO library. I haven't actually done an analysis of the code so I have no idea how feasible that is. @siteshwar, is it your impression that ksh depends so heavily on SFIO functionality we can't simply remove that as a dependency and instead have ksh use the OS provided stdio subsystem? Because I'd rather do that than hack away at the SFIO code to remove functionality not needed by ksh.

**Comment by siteshwar** [comment]
It won't be as easy to remove dependency over sfio. I will not start replacing it with stdio until we have switched to new build system and fixed all the test cases.

**Comment by siteshwar** [comment]
All test cases should be passing now. I have [left a comment](https://github.com/siteshwar/ast/blob/a491f1b944a1b3a6331362f1a4151bf100ae9777/src/lib/libast/include/ast.h#L450-L453) in the code about the workaround for https://github.com/att/ast/pull/107#issuecomment-342561202

**Comment by krader1961** [comment]
This fails to build on FreeBSD 11 and macOS 10.12.6 with errors such as this:

```
/usr/include/sys/_types/_socklen_t.h:30:28: error: cannot combine with previous 'type-name' declaration specifier
typedef __darwin_socklen_t      socklen_t;
                                ^
./FEATURE/poll:88:28: note: expanded from macro 'socklen_t'
#define socklen_t       unsigned int    /* default for type socklen_t */
                                 ^
```

There's probably a simple fix which I'll try to find later today.

P.S., I've also looked into adding macOS to the Travis env matrix but it's not obvious how to do so when Docker based configs are present. If anyone has experience with such configs and can help that would be great.

**Comment by siteshwar** [comment]
I will have to clean up ```src/cmd/ksh93/features/poll``` at some point, it's very likely I will end up removing it. For now below patch should suffice :
```
diff --git a/src/cmd/ksh93/features/poll b/src/cmd/ksh93/features/poll
index 3a0d148..c4fd07e 100644
--- a/src/cmd/ksh93/features/poll
+++ b/src/cmd/ksh93/features/poll
@@ -4,7 +4,6 @@ lib     select,poll,socket
 lib    htons,htonl sys/types.h sys/socket.h netinet/in.h
 lib    getaddrinfo sys/types.h sys/socket.h netdb.h
 typ    fd_set sys/socket.h sys/select.h
-typ    socklen_t unistd.h sys/socket.h = unsigned int
 tst    pipe_socketpair note{ use socketpair() for peekable pipe() }end execute{
        #include <ast.h>
        #include <signal.h>
```

I will add it to this pull request.

**Comment by krader1961** [comment]
LGTM. This now builds on macOS and FreeBSD.

N.B., It also built after I applied PR #109 on top of this PR (after fixing a merge conflict).
