### ISSUE TITLE
mkostemps is not available on older systems

### ISSUE THREAD

**Issue by ryandesign** [att/ast#938]
**Description of problem:**

ksh fails to build on slightly older systems, due to the use of `mkostemps`.

**Ksh version:**

20181007

**How reproducible:**

Always

**Steps to reproduce:**
1. Build latest ksh on OS X 10.11 El Capitan

**Actual results:**

```
../ast-7a4881196dac4ea2264ec0e8b95e6db7b4965ef9/src/lib/libast/path/pathtemp.c:92:15: error: implicit declaration of function 'mkostemps' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
        *fd = mkostemps(template, 0, open_flags);
              ^
```

**Expected results:**

Successful build.

**Additional info:**

**Comment by ryandesign** [comment]
As far as I can tell, based on the existence of the manpage for them, `mkostemp` and `mkostemps` made their first appearance in macOS version 10.13.

**Comment by krader1961** [comment]
> As far as I can tell, based on the existence of the manpage for them, mkostemp and mkostemps made their first appearance in macOS version 10.13.

FWIW that is not true. I've been building this project on macOS 10.12 for the past year. But I don't doubt that `mkostemps()` isn't available on older releases. And issues like https://bugs.freedesktop.org/show_bug.cgi?id=102986 make it clear that this type of issue is complicated.

**Comment by ryandesign** [comment]
> FWIW that is not true. I've been building this project on macOS 10.12 for the past year. But I don't doubt that `mkostemps()` isn't available on older releases.

Yes we did get a successful build on 10.12. I guess Apple just forgot to add them to the manpage for 10.12.

> And issues like https://bugs.freedesktop.org/show_bug.cgi?id=102986 make it clear that this type of issue is complicated.

Well, that issue was only complicated because the developer kept arguing without understanding how weak linking works on macOS. And that situation only arises when a user wishes to build for an older version of macOS on a newer version of macOS, which isn't as common as just building on the same OS version that you want to run on.

**Comment by krader1961** [comment]
Argh! Yes, if the system doesn't provide the function we need to provide not only an implementation but also a prototype. Which I realized when implementing a fallback for `eaccess()` but not for the change where I implemented a `mkostemp()` fallback. That's because my test using the fallback did not consider the platform headers may not have provided a prototype. /facepalm

**Comment by siteshwar** [comment]
Build is failing on OBS after change for this issue:

```
[  110s] ../src/lib/libast/misc/fallbacks.c:27:15: error: static declaration of 'mkostemp' follows non-static declaration
[  110s]  static_fn int mkostemp(char *template, int oflags) {
[  110s]                ^~~~~~~~
[  110s] In file included from /usr/include/features.h:419:0,
[  110s]                  from /usr/include/x86_64-linux-gnu/sys/types.h:25,
[  110s]                  from ./config_ast.h:217,
[  110s]                  from ../src/lib/libast/misc/fallbacks.c:5:
[  110s] /usr/include/stdlib.h:627:12: note: previous declaration of 'mkostemp' was here
[  110s]  extern int __REDIRECT (mkostemp, (char *__template, int __flags), mkostemp64)
[  110s]             ^
```

**Comment by krader1961** [comment]
Gotta love standardization. On most platforms `mkostemp()` is declared in *stdlib.h* but on macOS it's in *unistd.h*. So the feature test for that function was failing on most platforms. This wasn't caught because on my systems and Travis we're doing debug builds which made the overlooked `static_fn` a no-op. But on OBS we're doing production builds where that becomes `static` thus triggering the declaration mismatch. Should be fixed now.

**Comment by siteshwar** [comment]
OBS builds are fixed now. Thanks for taking care of it.
