### PR TITLE
Fix compiler error on OS X 10.6

### LINKED ISSUE #1462: error: implicit declaration of function 'ERROR_dictionary' is invalid in C99
**Description of problem:**

ksh fails to build on Mac OS X 10.6 with clang 9

**Ksh version:**

2020.0.0 and latest master (43d1853)

**How reproducible:**

Always

**Steps to reproduce:**
1. Build ksh on Mac OS X 10.6 with clang 9

**Actual results:**

```
../att-ast-43d1853/src/lib/libdll/dlfcn.c:287:31: error: implicit declaration of function 'ERROR_dictionary' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
static const char e_cover[] = T("cannot access covered library");
                              ^
../att-ast-43d1853/src/lib/libdll/dlfcn.c:37:14: note: expanded from macro 'T'
#define T(x) ERROR_dictionary(x)
             ^
```

[Build log for 2020.0.0](https://build.macports.org/builders/ports-10.6_x86_64-builder/builds/17146/steps/install-port/logs/stdio)
[Build log for 43d1853](https://build.macports.org/builders/ports-10.6_x86_64-builder/builds/17147/steps/install-port/logs/stdio)

**Expected results:**

Successful build

**Additional info:**

It builds fine on later versions of Mac OS X.

### PR DESCRIPTION
**Pull request by krader1961**
Mac OS X 10.6 (Snow Leopard) causes symbol `ERROR_dictionary` in
src/lib/libdll/dlfcn.c to be evaluated. Since that symbol isn't defined it
results in a compilation error. Add the identity mapping that is present
in the rest of the source code.

Fixes #1462

### CODE REVIEW

**Comment by krader1961** [comment]
@ryandesign I booted my ancient OS X 10.6 VM but it isn't able to install Meson using the Homebrew environment it already had.  Sorry, I know that using Homebrew rather than MacPorts is heretical. :smile: Is it possible for you to verify that this change fixes the build for you? If not I'll just merge it and you can then report back if it didn't fix the build for you.

**Comment by krader1961** [comment]
Why haven't the new owners of this project closed this pull-request? Could it be because they aren't competent to manage this project? Nah, that can't possibly be the reason. /snark

I also wonder what they intend to do with issue #1462 that resulted in this P.R.

**Comment by gordonwoodhull** [comment]
In any case, the PR is only relevant to ksh2020.

**Comment by gordonwoodhull** [comment]
@krader1961, we at AT&T are not actively maintaining this repo - everyone should fork from here if they want to continue development.

Thanks for pointing out that this PR should be closed as part of #1466. I hope that you will take your fork of ksh to a new repo, or that others who prefer ksh2020 will continue your work if you are no longer interested.
